---
name: Automated Version Bump for AsyncAPI
description: Automated version bump for AsyncAPI documents to follow Semantic Versioning.
runs:
  using: node12
  main: src/index.js
inputs:
  tag-prefix:
    description: 'Prefix that is used for the git tag'
    default: ''
    required: false
  minor-wording:
    description: |
      Words list that trigger a minor version bump.
      Use "," to separate multiple words.
    default: 'feat'
    required: false
  major-wording:
    description: |
      Words list that trigger a major version bump.
      Use "," to separate multiple words.
    default: 'feat!,fix!,refactor!'
    required: false
  patch-wording:
    description: |
      Words list that trigger a patch version bump.
      Use "," to separate multiple words.
    default: 'fix'
    required: false
  release-candidate-wording:
    description: |
      Words list that trigger a release candidate version bump.
      Use "," to separate multiple words.
    default: 'next'
    required: false
  skip-tag:
    description: 'Avoid to add a TAG to the version update commit'
    default: 'true'
    required: false
  skip-commit:
    description: 'Avoid to add a commit after the version is bumped'
    default: 'false'
    required: false
  skip-push:
    description: 'If true, skip pushing any commits or tags created after the version bump'
    default: 'false'
    required: false
  path-to-asyncapi:
    description: 'Path to the AsyncAPI document to bump'
    default: './asyncapi.json'
    required: false
  target-branch:
    description: 'A separate branch to perform the version bump on'
    default: ''
    required: false
  pre-release-id:
    description: 'Set a custom id for pre-release build'
    default: 'next'
    required: false
  dry-run:
    description: 'This makes sure that no changes are made to the AsyncAPI document and no changes are committed. Use this to determine if any bumps is necessary.'
    default: 'false'
    required: false
  commit-message:
    description: |
      Set a custom commit message for version bump commit.
      Use {{version}} as a placeholder for the new version.
    default: 'ci: version bump to {{version}}'
    required: false
  release-commit-message-regex:
    description: |
      Set the regex to match release commit messages. Usually it is similar to `commit-message`. Use {{version}} as a placeholder for the new version.
    default: 'ci: version bump to {{version}}'
    required: false
outputs:
  wasBumped:
    description: 'Boolean to check if document was bumped'
  newVersion:
    description: 'The new version of the AsyncAPI document'
  oldVersion:
    description: 'The old version of the AsyncAPI document'
